### ISSUE TITLE
Fix calculating Fragment execution duration

### ISSUE THREAD

**Issue by marcinus** [Knotx/knotx-fragments#139]
**Describe the bug**
Currently, Fragment execution's duration is calculated using the following procedure in `EventLog`:
```
public long getEarliestTimestamp() {
    return operations.stream()
        .mapToLong(EventLogEntry::getTimestamp)
        .min()
        .orElse(0);
  }
```
However, the earliest EventLogEntry is recorded **after** the first node's execution!
If the first node in the graph happens to be time-consuming, the calculated duration will be significatly underestimated.

**Expected behavior**
Fragment execution's duration should be calculated from the admission to TaskEngine to the return from it.

**Comment by tomaszmichalak** [comment]
This is fixed. Right now each node logs when starts and ends.
