### ISSUE TITLE
Move ExposePayloadActionFactory from GraphQL example to core.

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-fragments#173]
**Is your feature request related to a problem? Please describe.**
Please move the `ExposePayloadActionFactory` action from the knotx-example repository to knotx-fragments. Please rename this action to `CopyPayloadKeyActionFactory`.

**Additional context**
Please implement tests, documentation and refactor.

**Comment by marcinus** [comment]
To remove the action from `knotx-example-project`, a new release is required.
