### ISSUE TITLE
Error handling for fragment processing

### ISSUE THREAD

**Issue by marcinkp** [Knotx/knotx-fragments#18]
**Describe the bug**

Knotx returned Status Code: 204 No Content for invalid fragment processig

**To Reproduce**
1. Define task with one action 
2. Do not handle transitions in task definition
3. Action defined for task should return FragmentResult.ERROR_TRANSITION 

**Expected behavior**
Knotx returned Status Code: 204 No Content

**Comment by Skejven** [comment]
Fixed in #22
