### ISSUE TITLE
Change HtmlSplitterRoutingHandlerFactory config name

### ISSUE THREAD

**Issue by Skejven** [Knotx/knotx-fragments#33]
Current name `fragmentsProviderHtmlSplitter` is long and not very descriptive.

**Describe the solution you'd like**
Change the name to e.g. `htmlToFragmentsSplitter`.

**Additional context**
Please remember about updating configs in `knotx-stack` and `knotx-example-project`.

**Comment by marcinkp** [comment]
How about:
fragmentsProviderHtmlSplitter -> htmlFragmentsSupplier
singleFragmentSupplier -> singleFragmentSupplier


fragmentsAssemblerHandler -> fragmentsAssembler

**Comment by tomaszmichalak** [comment]
Fixed.
