### ISSUE TITLE
Add Circuit Breaker action logs

### ISSUE THREAD

**Issue by marcinkp** [Knotx/knotx-fragments#58]
**Issue background.**
Every Single Action in Knot.x can be wrapped by Circuit Breaker. Circuit Breaker keeps track of the number of failures and opens the circuit when a threshold is reached and fallback is executed
From **action logs** perspective CB should log: 
 - logs produced by wrapped Action  
 - execution duration time
 -  number of tries
 - failure details
 - fallback if executed.

Circuit Breaker supports the following failures:
 - the exception is thrown by wrapped Action
 - timeout

The timeout can be set on the CB level. it means that every Action execution which takes more than timeout will be treated as a failure. It also means that CB will not collect any log produced by the Action itself.  If you want to be sure that timeout information will be logged you need to handle it on the wrapped action level. For example, HTTP-action can have its own timeout for calling external services. It can be handled internally and timeout exception can be thrown which will be handled on the Circuit Breaker mechanism.

**Solution**
Current action log structure:
```
{
  _alias: A'
  _logs: {}
  _doAction [
    {
      _alias: A''
      _logs: {}
      _doAction {
        _alias: A'''
        _logs: {}
      }
    }
  ]
} 
```
This structure for **doAction** should be extended by **metadata**. In addition name can be also changed. for **invocations**

Logs specific for CB can have the structure:

```
  logs: {
    numbeOfTrys: 3
    fallback: "TimeoutException. Cannot execute http action." 
  },
```
**numbeOfTrys** is a total number of retries.  
**fallback** is optional and appears only if happen.

The final Action Log for CB will look like:
```
{
  alias: "CB",
  logs: {
    numbeOfTrys: 3
    fallback: "TimeoutException. Cannot execute http action." 
  },
  invocations: [
    {
      metadata: {
        duration: 10,
        success: false,
        error: {
          code: "TIMEOUT",
          message: ""
        }
      },
      doActionLog: {
        // node logs
      }
    }
  ]
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by tomaszmichalak** [comment]
`numbeOfTrys` -> `retriesCount`
- start with `0`, first inovation it is still `0`
- next retries, `++retriesCount`

**Comment by marcinkp** [comment]
I suggest `invocationCount` starts with `1`

**Comment by tomaszmichalak** [comment]
Implemented.
