### ISSUE TITLE
Limit number of WebClient instances

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-fragments#72]
**Is your feature request related to a problem? Please describe.**
WebClient invokes external sources to fetch some data or modify some values. Knot.x HTTP Server handles incoming requests with custom handlers. Each handler can contain some business logic that interacts with external data sources via WebClient.

Moreover, Knot.x Fragments allows defining business logic in the form of a graph. Each graph node can communicate with some external resource via WebClient. HTTP Action fetches data from APIs via GET requests.

We need to revalidate when we create WebClient instances and where we can cache some objects.

**Describe the solution you'd like**
Design session required.

**Additional context**
Related modules:
- https://github.com/Knotx/knotx-data-bridge
- https://github.com/Knotx/knotx-repository-connector/tree/master/http
- https://github.com/Knotx/knotx-server-http

**Comment by marcinus** [comment]
As MVP, we will go for @Cachable annotation in HttpActionFactory.
It's required to ensure that the HttpAction can be reused.

**Comment by marcinus** [comment]
To consider: how "cacheble" is WebClient? Is configuration similar between different actions?

**Comment by marcinus** [comment]
The default behaviour of `@Cacheable` annotation is to cache using action alias as key.
As long as an alias is unique, this should not lead to inconsistencies (**requires validation**).
`WebClient` instances can be cached on the factory level with `WebClientOptions` as key (transformed to JSON - `equals` and `hashCode`).

**Comment by marcinus** [comment]
`WebClient` caching is introduced in #99. However, the cache size is not configurable.
Consider creating a shared WebClientCache available to all action factories (may require an API change).

**Comment by tomaszmichalak** [comment]
Implemented in `io.knotx.fragments.handler.action.http.HttpActionFactory`.
