### ISSUE TITLE
InMemoryCacheAction log

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-fragments#76]
**Is your feature request related to a problem? Please describe.**
Add an [action node log](https://github.com/Knotx/knotx-fragments/pull/55) support for In-memory Cache Action.

**Describe the solution you'd like**
The log should contain:
- cache key (`key`)
- cache value if available (`cacheValue`)
- value from `doAction` if not found in the cache (`newValue`)

All the above entries should appear when `INFO` log level is set.

**Additional context**
Consider the situation when `doAction` action throws some error or responds with `_error` transition. Check also [this PR](https://github.com/Knotx/knotx-fragments/pull/45/files#diff-d48decbc78ea648abf1a06fcb9681288).

**Comment by marcinus** [comment]
Wondering whether this feature should have a configurable log level (just like CircuitBreakerActionFactory has)
